version: '3.8'

services:
  site:
    build:
      context: .
      dockerfile: nginx.prod.dockerfile
    ports:
      - 443:443
    depends_on:
      - openvpn-client
      - mysql
      - php
      - assets

  php:
    build:
      context: .
      dockerfile: php.prod.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}

  assets:
    image: node:current-alpine
    volumes:
      - ./src:/var/www/html
    command: ["/bin/sh", "-c", "npm install && npm run production"]
    working_dir: /var/www/html
